export { DialogRoot as Dialog, DialogClose, DialogTrigger } from 'reka-ui'
export { default as DialogContent } from './dialog-content.vue'
export { default as DialogDescription } from './dialog-description.vue'
export { default as DialogFooter } from './dialog-footer.vue'
export { default as DialogHeader } from './dialog-header.vue'
export { default as DialogOverlay } from './dialog-overlay.vue'
export { default as DialogScrollContent } from './dialog-scroll-content.vue'
export { default as DialogTitle } from './dialog-title.vue'
